### ISSUE TITLE
Pypi install fails to install all needed packages

### ISSUE THREAD

**Issue by Skelmis** [diarts/aioyoutube#2]
Not entirely sure how pypi works with installing packages however when downloading `aioyoutube` with `pip install aioyoutube` it fails to install a required package which needs to be installed in order to use the package `rfc3339`
If this could get added into im assuming requirements.txt that'd be great

**Comment by diarts** [comment]
> Not entirely sure how pypi works with installing packages however when downloading `aioyoutube` with `pip install aioyoutube` it fails to install a required package which needs to be installed in order to use the package `rfc3339`
> If this could get added into im assuming requirements.txt that'd be great

rfc339 package now autoinstalling when you install aioyoutube, use aioyoutube 0.1.6. Thanks for your notice!

**Comment by Skelmis** [comment]
Cheers!
